# Generated by Django 5.0.1 on 2024-11-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_create_date_alter_blog_update_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='like',
            new_name='likes',
        ),
    ]
