# Generated by Django 5.0.1 on 2024-11-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liked_by',
        ),
    ]
