# Generated by Django 5.0.1 on 2024-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='urlImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
